/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CasparFiles = CasparFile[];

export interface CasparFile {
	name: string;
	type: string;
	size: number;
	changed: number;
	frames: number;
	frameTime: string;
	frameRate: number;
	duration: number;
}
