/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ChecklistGroup = ChecklistTask[];

export interface Checklist {
	extraContent: ChecklistGroup;
	techStationDuties: ChecklistGroup;
	stageTechDuties: ChecklistGroup;
	audioEngineerDuties: ChecklistGroup;
	special: ChecklistGroup;
}
export interface ChecklistTask {
	name: string;
	shortName?: string;
	complete: boolean;
}
