/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CurrentIntermission {
	preOrPost: 'pre' | 'post';
	content: (
		| {
				type: 'adBreak';
				ads: {
					id: number;
					name: string;
					adType: 'VIDEO' | 'IMAGE';
					filename: string;
					duration: string;
					order: number;
					suborder: number;
					sponsorName: string;
					type: 'ad';
					state: {
						canStart: boolean;
						started: boolean;
						canComplete: boolean;
						completed: boolean;
						durationFrames: number;
						framesLeft: number;
						frameNumber: number;
						fps: number;
						hasFile: boolean;
					};
				}[];
				id: number;
				state: {
					canStart: boolean;
					cantStartReason: string;
					started: boolean;
					canComplete: boolean;
					completed: boolean;
				};
		  }
		| {
				id: number;
				interviewees: string[];
				interviewers: string[];
				duration: string;
				order: number;
				subject: string;
				suborder: number;
				type: 'interview';
		  })[];
}
