/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OotBingo3Aboard {
	cells: {
		slot: string;
		colors: string;
		name: string;
	}[];
	selectedLine:
		| 'none'
		| 'col1'
		| 'col2'
		| 'col3'
		| 'col4'
		| 'col5'
		| 'row1'
		| 'row2'
		| 'row3'
		| 'row4'
		| 'row5'
		| 'tl-br'
		| 'bl-tr';
	lineFocused: boolean;
	cardHidden: boolean;
	embiggen: boolean;
	[k: string]: any;
}
