/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SmalttpData = Goal[];

export interface Goal {
	name: string;
	state: number;
	maxState: number;
	isBoss: boolean;
	highlight?: boolean;
}
