/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StreamStatus {
	'bytes-per-sec': number;
	'encode-skipped'?: number;
	'encode-total'?: number;
	fps: number;
	'kbits-per-sec': number;
	'num-dropped-frames': number;
	'num-total-frames': number;
	recording: boolean;
	'render-skipped'?: number;
	'render-total'?: number;
	strain: number;
	'stream-timecode': string;
	streaming: boolean;
	'total-stream-time': number;
}
